## Required ENV variables in CircleCI account:
# DOCKER_USER
# DOCKER_PASSWORD

version: 2
jobs:
  # Run Docker Build as a basic check to know if Dockerfiles don't produce any error
  docker:
    working_directory: ~/docker
    docker:
      - image: docker:18-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Dependencies
          command: apk add make bash
      - run:
          name: Build Docker images
          command: make build
      - run:
          name: Show produced Docker images
          command: docker images
      - run:
          name: Login to Docker Hub
          command: docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
      - run:
          name: Deploy image to Docker Hub
          command: make push

workflows:
  version: 2
  # Build and Push Docker images
  docker-build-push:
    jobs:
      - docker
  # Build and Push nightly 'dev' Docker images from 'master' branch
  nightly-dev-push:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - docker

experimental:
  notify:
    branches:
      only:
        - master
        - /v[0-9]+\.[0-9]+/
