version: 2
jobs:
  # Run Docker Build as a basic check to know if Dockerfiles don't produce any error
  docker-build:
    working_directory: ~/docker
    docker:
      - image: docker:18-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: apk add make bash
      - run:
          name: Build Docker images
          command: make build
      - run:
          name: Show produced Docker images
          command: docker images

workflows:
  version: 2
  k8s:
    jobs:
      - docker-build

experimental:
  notify:
    branches:
      only:
        - master
